import '../models/course.dart';

// List of sample courses
final List<Course> courses = [
  Course(
    id: '1',
    title: 'International Commercial Arbitration: London Practice',
    instructor: 'Dr. Sarah Mitchell, QC',
    rating: 4.9,
    reviewCount: 2847,
    duration: '16 hours',
    studentCount: 12450,
    price: 299,
    originalPrice: 599,
    category: 'arbitration',
    level: 'Advanced',
    image: 'assets/images/arbitration-london.jpg',
    isPopular: true,
    isBestseller: true,
  ),
  Course(
    id: '2',
    title: 'Mediation Fundamentals for Business Disputes',
    instructor: 'Prof. Michael Chen',
    rating: 4.8,
    reviewCount: 1923,
    duration: '12 hours',
    studentCount: 8765,
    price: 199,
    originalPrice: 399,
    category: 'mediation',
    level: 'Beginner',
    image: 'assets/images/mediation-fundamentals.jpg',
    isPopular: true,
  ),
  Course(
    id: '3',
    title: 'Dubai International Arbitration Center (DIAC) Rules',
    instructor: 'Ahmed Al-Rashid, Esq.',
    rating: 4.7,
    reviewCount: 1456,
    duration: '10 hours',
    studentCount: 5432,
    price: 249,
    category: 'arbitration',
    level: 'Intermediate',
    image: 'assets/images/diac-rules.jpg',
  ),
  Course(
    id: '4',
    title: 'Commercial Law Essentials for Non-Lawyers',
    instructor: 'Lisa Thompson, LLB',
    rating: 4.6,
    reviewCount: 2134,
    duration: '14 hours',
    studentCount: 9876,
    price: 179,
    originalPrice: 299,
    category: 'commercial-law',
    level: 'Beginner',
    image: 'assets/images/commercial-law.jpg',
  ),
  Course(
    id: '5',
    title: 'Advanced Mediation Techniques',
    instructor: 'Dr. Aisha Patel',
    rating: 4.7,
    reviewCount: 987,
    duration: '18 hours',
    studentCount: 3456,
    price: 399,
    category: 'mediation',
    level: 'Advanced',
    image: 'assets/images/advanced-mediation.jpg',
  ),
  Course(
    id: '6',
    title: 'Corporate Compliance & Risk Management',
    instructor: 'Robert Williams, CPA',
    rating: 4.5,
    reviewCount: 1678,
    duration: '20 hours',
    studentCount: 6543,
    price: 329,
    originalPrice: 549,
    category: 'compliance',
    level: 'Intermediate',
    image: 'assets/images/compliance-risk.jpg',
  ),
  Course(
    id: '7',
    title: 'International Investment Arbitration',
    instructor: 'Prof. Elena Rodriguez',
    rating: 4.8,
    reviewCount: 892,
    duration: '22 hours',
    studentCount: 2987,
    price: 449,
    category: 'arbitration',
    level: 'Advanced',
    image: 'assets/images/investment-arbitration.jpg',
    isPopular: true,
  ),
  Course(
    id: '8',
    title: 'Construction Dispute Resolution',
    instructor: 'David Kumar, PE',
    rating: 4.7,
    reviewCount: 1245,
    duration: '15 hours',
    studentCount: 4321,
    price: 279,
    category: 'corporate-disputes',
    level: 'Intermediate',
    image: 'assets/images/construction-dispute.jpg',
  ),
  Course(
    id: '9',
    title: 'Ethics in International Arbitration',
    instructor: 'Dr. Marie Dubois',
    rating: 4.6,
    reviewCount: 756,
    duration: '8 hours',
    studentCount: 2165,
    price: 159,
    category: 'compliance',
    level: 'Beginner',
    image: 'assets/images/ethics-arbitration.jpg',
  ),
];